### ISSUE TITLE
Stworzenie bazy danych według diagramu UML

### ISSUE THREAD

**Issue by 0xuser** [0xuser/classifieds-map#4]
stworzenie bazy według diagramu UML
https://github.com/0xuser/classifieds-map/blob/master/img/Baza.xml

**Comment by ilinoyer** [comment]
Baza danych stworzona. 

@drakian003 
@wojciech-jakub 

Proszę o weryfikacje.

**Comment by wojciech-jakub** [comment]
Z uwagi na sposób porównywania znaków w bazie danych.
Skoro produkt będzie skierowany głównie do polskich klientów, zmieniłem metodę porównywania znaków na "utf8_polish_ci". Zmieniłem to z uwagi na dbałość o szczególy. Należy poprawić -> w kazdej tabeli dane id  było inkrementowane.
Dziękuje, pozdrawiam WJ.
